### ISSUE TITLE
PHP 7.1

### ISSUE THREAD

**Issue by octalmage** [wpengine/phpcompat#100]
PHP 7.1<br>
http://ift.tt/2i6OLUf<br><p>Replies: 0</p>
<p>Has anyone done any testing to see if the later versions of wordpress and MySQL&nbsp;work with PHP 7.1?</p>
<br><br>
via WordPress.org Forums &raquo; All Topics http://ift.tt/2gps7Vy<br>
January 03, 2017 at 11:26AM

**Comment by thiagopelizoni** [comment]
Wordpress used to work well on PHP 7.1 as far unit tests says [](https://travis-ci.org/aaronjorbin/develop.wordpress/jobs/186252468)

The main problem howewer lies in all third-party plugins that must updated by their developers in order to work properly in this version.

You should try to run [php7cc](https://github.com/sstalle/php7cc) in your project.

**Comment by jrfnl** [comment]
Or just run the PHPCompatibility checker which is used under the hood of this plugin to also test for PHP 7.1. The tool covers most of PHP 7.1 and has done so from before PHP 7.1 was released.
On that note: the first checks for PHP 7.2 specific things have even been added already.
