### ISSUE TITLE
Whitelist plugins with current Stripe PHP library (WP Simple Pay Lite & Pro, etc).

### ISSUE THREAD

**Issue by pderksen** [wpengine/phpcompat#89]
Developer of [WP Simple Pay Lite](https://github.com/moonstonemedia/WP-Simple-Pay-Lite-for-Stripe) & Pro here.

We include the [Stripe PHP library](https://github.com/stripe/stripe-php) with our Lite & Pro plugins, and we stay pretty current. Stripe PHP v4.1.1 or higher in both, and I'm testing with the latest (v4.3.0) in both locally with the same results.

We're getting these errors:

```
FILE: .../wp-content/plugins/wp-simple-pay-pro-for-stripe/vendor/stripe/stripe-php/lib/StripeObject.php
--------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
--------------------------------------------------------------------------------------------------------------------------------------------------------
 268 | WARNING | Method name "StripeObject::__toJSON" is discouraged; PHP has reserved all method names with a double underscore prefix for future use
 283 | WARNING | Method name "StripeObject::__toArray" is discouraged; PHP has reserved all method names with a double underscore prefix for future use
--------------------------------------------------------------------------------------------------------------------------------------------------------
```

https://github.com/stripe/stripe-php/blob/d414571b18c2ba87279c7083acfdc6497f630da8/lib/StripeObject.php#L268-L268

https://github.com/stripe/stripe-php/blob/d414571b18c2ba87279c7083acfdc6497f630da8/lib/StripeObject.php#L283-283

Not sure if a tweak to the PHP 7 compatibility plugin or to the Stripe PHP library is in order here. Or possibly a whitelist of plugins with the Stripe PHP library included.

**Comment by octalmage** [comment]
Interesting, I looked into this warning and it looks like it comes from this page: 

http://php.net/manual/en/language.oop5.magic.php

Which is very confusing. People [here](http://stackoverflow.com/questions/9701186/user-defined-magic-methods-what-is-documented-magic-functionality) take it to mean that you shouldn't use double underscore, which is the way the PHP Compatibility library interpreted it. 

I might bring this up with the Stripe team and see what they have to say. My worry is that these methods are public so others might be relying on them, but they're [meant for debugging](https://github.com/stripe/stripe-php/issues/42) so hopefully they aren't used in production. 

At the very least we could just whitelist that path, but I would like to avoid doing that if possible since it is a valid warning. It doesn't imply incompatibility, just something to watch.

**Comment by octalmage** [comment]
Actually, I'm just going to whitelist that file. Since these functions aren't used anywhere in the Stripe library, they're harmless.

**Comment by pderksen** [comment]
@octalmage Interesting find, and in any case thanks for whitelisting the file for now. 👍
